export const CHANGE_SECOND_DIALOG_PARAMS = "CHANGE_SECOND_DIALOG_PARAMS";
export const CHANGE_DIALOG_PARAMS = "CHANGE_DIALOG_PARAMS";
export const SET_SWAP_POOL_LIST = "SET_SWAP_POOL_LIST";
export const SET_SWAP_PERSON_DATA = "SET_SWAP_PERSON_DATA";
export const SET_SWAP_TOTAL_DATA = "SET_SWAP_TOTAL_DATA";
export const SWAP_MINING_DRAW_GAS = "SWAP_MINING_DRAW_GAS";
// 流动性
export const CHANGE_INPUT_DIALOG_PARAMS = "CHANGE_INPUT_DIALOG_PARAMS";
export const SET_LIQUIDITY_POOLLIST = "SET_LIQUIDITY_POOLLIST";
export const SET_CURR_LPTOKEN_INFO = "SET_CURR_LPTOKEN_INFO";
