export const SET_SELECTOR_DIALOG_PARAMS = "SET_SELECTOR_DIALOG_PARAMS";
export const SET_WALLET_DIALOG_PARAMS_STATUS =
  "SET_WALLET_DIALOG_PARAMS_STATUS";
export const SET_CALLBACK_DIALOG_PARAMS_STATUS =
  "SET_CALLBACK_DIALOG_PARAMS_STATUS";
export const CHANGE_OPERATE_STATUS = "CHANGE_OPERATE_STATUS";
