export const SET_SELECTOR_DIALOG_PARAMS = "SET_SELECTOR_DIALOG_PARAMS";
export const SET_WALLET_DIALOG_PARAMS = "SET_WALLET_DIALOG_PARAMS";
export const SET_SECOND_DIALOG_PARAMS = "SET_SECOND_DIALOG_PARAMS";
export const SET_NFT_STAKE_LIST = "SET_NFT_STAKE_LIST";
